# Generated by Django 4.2.16 on 2024-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
