# Generated by Django 4.2.16 on 2024-10-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acceso', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
