# Generated by Django 4.2.16 on 2024-10-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acceso', '0006_remove_user_cedula_remove_user_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
