// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOU-NAN1pnSn4pr2dFqYUtichZThosTmA',
    appId: '1:958777339141:web:80cee7c9cb25d921095b6c',
    messagingSenderId: '958777339141',
    projectId: 'restaurapp-ae6c5',
    authDomain: 'restaurapp-ae6c5.firebaseapp.com',
    storageBucket: 'restaurapp-ae6c5.appspot.com',
    measurementId: 'G-TEQFKGX195',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_6OOul6P9fxtZh9cOkFq5y_8HSAKaYA',
    appId: '1:958777339141:android:de3bbb5b188c8d40095b6c',
    messagingSenderId: '958777339141',
    projectId: 'restaurapp-ae6c5',
    storageBucket: 'restaurapp-ae6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJAM-8zHecjYYzMUVSOSfADlLRsQF1dCc',
    appId: '1:958777339141:ios:ef40a71b1380e0ed095b6c',
    messagingSenderId: '958777339141',
    projectId: 'restaurapp-ae6c5',
    storageBucket: 'restaurapp-ae6c5.appspot.com',
    iosBundleId: 'com.example.restaurApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJAM-8zHecjYYzMUVSOSfADlLRsQF1dCc',
    appId: '1:958777339141:ios:ef40a71b1380e0ed095b6c',
    messagingSenderId: '958777339141',
    projectId: 'restaurapp-ae6c5',
    storageBucket: 'restaurapp-ae6c5.appspot.com',
    iosBundleId: 'com.example.restaurApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOU-NAN1pnSn4pr2dFqYUtichZThosTmA',
    appId: '1:958777339141:web:dc08202af86cf892095b6c',
    messagingSenderId: '958777339141',
    projectId: 'restaurapp-ae6c5',
    authDomain: 'restaurapp-ae6c5.firebaseapp.com',
    storageBucket: 'restaurapp-ae6c5.appspot.com',
    measurementId: 'G-H54SWP4503',
  );
}
