"""
Django settings for deli_zone project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps propias
    "deli_zone_app",
    "menu",
    "carrito",
    "contacto",
    "configuracion_usuarios",
    "ubicacion",
    "pasarela_pagos",
    "pedidos_cliente",
    # Panel de administrador
    "dashboard",
    "productos",
    "gestion_contacto",
    "configuracion_sitio",
    # CSS
    "bootstrap5",
    # Test
    "pruebas",
    # Administracion de usuarios y permisos
    "gestion_acceso",
    # Rest para crear apis
    'rest_framework',
    # Apis
    # 'pedidos_api',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "deli_zone.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Funciones propias
                # Imagen del administrador y del cliente
                "carrito.carrito.datos_carrito",
                "deli_zone_app.contexto_global.excluir_paths_sitio",
                "deli_zone_app.contexto_global.imagen_cliente",
                "deli_zone_app.contexto_global.imagen_admin",
                "gestion_acceso.acceso.estado_login_usuario",
                # Configuraciones del sitio
                "deli_zone_app.contexto_global.logo_sitio",
                "deli_zone_app.contexto_global.fav_icon_sitio",
                "deli_zone_app.contexto_global.colores_sitio",
            ],
        },
    },
]

WSGI_APPLICATION = "deli_zone.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os 
from dotenv import load_dotenv 
load_dotenv() 

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') 
DEBUG = os.getenv('DEBUG') == 'True'

DATABASES = { 
    'default': { 
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'), 
        'NAME': os.getenv('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')), 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Manejo de sesiones
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Damos permisos de token
CSRF_TRUSTED_ORIGINS = ['https://2d30-181-53-12-20.ngrok-free.app']
